### ISSUE TITLE
Where are older versions gone?

### ISSUE THREAD

**Issue by pcav** [jhemmi/Physiocap3#3]
I can't see them on the list.
Thanks for clarifying.

**Comment by jhemmi** [comment]
Hello Paolo,
0.2 is the first version of Physiocap3 proposed on QGIS repo.
0.1 is under Github only.

Physiocap was the extension on QGIS 2.

Thanks for all your job on QGIS 3
Regards
Jean


Bien cordialement
Jean Hemmi

jhemmi.eu | Valoriser vos données
13 rue St Hubert 31500 Toulouse Tel :  +33 768 056 192
jhemmi.eu <http://objectifs.jhemmi.eu/> | Parcours π parcours.xyz | Extension
Physiocap pour QGIS
<https://github.com/jhemmi/QgisPhysiocapPlugin/wiki/C'est-quoi-Physiocap-%3F>
Chaîne You Tube <https://www.youtube.com/channel/UCH4X4q8JdaHGqDiptWchBJw>


Si ce courriel ne vous concerne pas, merci de nous le signaler. Nous vous
supprimerons de nos contacts.

2018-02-01 11:44 GMT+01:00 Paolo Cavallini <notifications@github.com>:

**Comment by pcav** [comment]
Thanks for clarifying. The recommended approach is to have different versions of the same plugin, instead of having a different one for Q3. Please consider this approach for compactness.

**Comment by jhemmi** [comment]
Ok I'll manage this way for my next delivery in Mars
Le 1 févr. 2018 11:55, "Paolo Cavallini" <notifications@github.com> a
écrit :
>
> Thanks for clarifying. The recommended approach is to have different
versions of the same plugin, instead of having a different one for Q3.
Please consider this approach for compactness.

**Comment by jhemmi** [comment]
Version Physiocap3 for QGIS 3 willliveinown live. 
For QGIS 2,x dev are stopped.
